name: Deploy Doc

on:
  push:
    # branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  # Build job
  build:
    # Specify runner +  build & upload the static files as an artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build charon docs
        id: build
        run: |
          mkdir doc
          cd charon/charon
          make doc
          mv target/doc ../../doc/charon
          # deployed at https://os-checker.github.io/charon-rudra/charon/charon/

      - name: Build charon-rudra docs
        run: |
          cargo doc --document-private-items --no-deps
          mv target/doc doc/charon-rudra
          ls -alh doc
          # deployed at https://os-checker.github.io/charon-rudra/charon-rudra/cargo_charon_rudra/

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: doc/

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
