name: Run Tests

on:
  push:

env:
  CARGO_TERM_COLOR: always
  FORCE_COLOR: "1"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up toolchain
        run: |
          rustup default nightly-2024-08-11
          rustup component add rustc-dev llvm-tools-preview
      - uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: sh test.sh
      - name: Run all tests
        run: cargo test --test diagnostics -- --color=always --nocapture
